CREATE TABLE clinica (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    nuit VARCHAR(50) NOT NULL,
    endereco VARCHAR(120) NOT NULL
   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
