CREATE TABLE especialidade(
  codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE pais(
  country_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  country VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;