INSERT INTO `pais` VALUES ('1', 'Afghanistan');
INSERT INTO `pais` VALUES ('2', 'Algeria');
INSERT INTO `pais` VALUES ('3', 'American Samoa');
INSERT INTO `pais` VALUES ('4', 'Angola');
INSERT INTO `pais` VALUES ('5', 'Anguilla');
INSERT INTO `pais` VALUES ('6', 'Argentina');
INSERT INTO `pais` VALUES ('7', 'Armenia');
INSERT INTO `pais` VALUES ('8', 'Australia');
INSERT INTO `pais` VALUES ('9', 'Austria');
INSERT INTO `pais` VALUES ('10', 'Azerbaijan');
INSERT INTO `pais` VALUES ('11', 'Bahrain');
INSERT INTO `pais` VALUES ('12', 'Bangladesh');
INSERT INTO `pais` VALUES ('13', 'Belarus');
INSERT INTO `pais` VALUES ('14', 'Bolivia');
INSERT INTO `pais` VALUES ('15', 'Brazil');
INSERT INTO `pais` VALUES ('16', 'Brunei');
INSERT INTO `pais` VALUES ('17', 'Bulgaria');
INSERT INTO `pais` VALUES ('18', 'Cambodia');
INSERT INTO `pais` VALUES ('19', 'Cameroon');
INSERT INTO `pais` VALUES ('20', 'Canada');
INSERT INTO `pais` VALUES ('21', 'Chad');
INSERT INTO `pais` VALUES ('22', 'Chile');
INSERT INTO `pais` VALUES ('23', 'China');
INSERT INTO `pais` VALUES ('24', 'Colombia');
INSERT INTO `pais` VALUES ('25', 'Congo, The Democratic Republic of the');
INSERT INTO `pais` VALUES ('26', 'Czech Republic');
INSERT INTO `pais` VALUES ('27', 'Dominican Republic');
INSERT INTO `pais` VALUES ('28', 'Ecuador');
INSERT INTO `pais` VALUES ('29', 'Egypt');
INSERT INTO `pais` VALUES ('30', 'Estonia');
INSERT INTO `pais` VALUES ('31', 'Ethiopia');
INSERT INTO `pais` VALUES ('32', 'Faroe Islands');
INSERT INTO `pais` VALUES ('33', 'Finland');
INSERT INTO `pais` VALUES ('34', 'France');
INSERT INTO `pais` VALUES ('35', 'French Guiana');
INSERT INTO `pais` VALUES ('36', 'French Polynesia');
INSERT INTO `pais` VALUES ('37', 'Gambia');
INSERT INTO `pais` VALUES ('38', 'Germany');
INSERT INTO `pais` VALUES ('39', 'Greece');
INSERT INTO `pais` VALUES ('40', 'Greenland');
INSERT INTO `pais` VALUES ('41', 'Holy See (Vatican City State)');
INSERT INTO `pais` VALUES ('42', 'Hong Kong');
INSERT INTO `pais` VALUES ('43', 'Hungary');
INSERT INTO `pais` VALUES ('44', 'India');
INSERT INTO `pais` VALUES ('45', 'Indonesia');
INSERT INTO `pais` VALUES ('46', 'Iran');
INSERT INTO `pais` VALUES ('47', 'Iraq');
INSERT INTO `pais` VALUES ('48', 'Israel');
INSERT INTO `pais` VALUES ('49', 'Italy');
INSERT INTO `pais` VALUES ('50', 'Japan');
INSERT INTO `pais` VALUES ('51', 'Kazakstan');
INSERT INTO `pais` VALUES ('52', 'Kenya');
INSERT INTO `pais` VALUES ('53', 'Kuwait');
INSERT INTO `pais` VALUES ('54', 'Latvia');
INSERT INTO `pais` VALUES ('55', 'Liechtenstein');
INSERT INTO `pais` VALUES ('56', 'Lithuania');
INSERT INTO `pais` VALUES ('57', 'Madagascar');
INSERT INTO `pais` VALUES ('58', 'Malawi');
INSERT INTO `pais` VALUES ('59', 'Malaysia');
INSERT INTO `pais` VALUES ('60', 'Mexico');
INSERT INTO `pais` VALUES ('61', 'Moldova');
INSERT INTO `pais` VALUES ('62', 'Morocco');
INSERT INTO `pais` VALUES ('63', 'Mozambique');
INSERT INTO `pais` VALUES ('64', 'Myanmar');
INSERT INTO `pais` VALUES ('65', 'Nauru');
INSERT INTO `pais` VALUES ('66', 'Nepal');
INSERT INTO `pais` VALUES ('67', 'Netherlands');
INSERT INTO `pais` VALUES ('68', 'New Zealand');
INSERT INTO `pais` VALUES ('69', 'Nigeria');
INSERT INTO `pais` VALUES ('70', 'North Korea');
INSERT INTO `pais` VALUES ('71', 'Oman');
INSERT INTO `pais` VALUES ('72', 'Pakistan');
INSERT INTO `pais` VALUES ('73', 'Paraguay');
INSERT INTO `pais` VALUES ('74', 'Peru');
INSERT INTO `pais` VALUES ('75', 'Philippines');
INSERT INTO `pais` VALUES ('76', 'Poland');
INSERT INTO `pais` VALUES ('77', 'Puerto Rico');
INSERT INTO `pais` VALUES ('78', 'Romania');
INSERT INTO `pais` VALUES ('79', 'Runion');
INSERT INTO `pais` VALUES ('80', 'Russian Federation');
INSERT INTO `pais` VALUES ('81', 'Saint Vincent and the Grenadines');
INSERT INTO `pais` VALUES ('82', 'Saudi Arabia');
INSERT INTO `pais` VALUES ('83', 'Senegal');
INSERT INTO `pais` VALUES ('84', 'Slovakia');
INSERT INTO `pais` VALUES ('85', 'South Africa');
INSERT INTO `pais` VALUES ('86', 'South Korea');
INSERT INTO `pais` VALUES ('87', 'Spain');
INSERT INTO `pais` VALUES ('88', 'Sri Lanka');
INSERT INTO `pais` VALUES ('89', 'Sudan');
INSERT INTO `pais` VALUES ('90', 'Sweden');
INSERT INTO `pais` VALUES ('91', 'Switzerland');
INSERT INTO `pais` VALUES ('92', 'Taiwan');
INSERT INTO `pais` VALUES ('93', 'Tanzania');
INSERT INTO `pais` VALUES ('94', 'Thailand');
INSERT INTO `pais` VALUES ('95', 'Tonga');
INSERT INTO `pais` VALUES ('96', 'Tunisia');
INSERT INTO `pais` VALUES ('97', 'Turkey');
INSERT INTO `pais` VALUES ('98', 'Turkmenistan');
INSERT INTO `pais` VALUES ('99', 'Tuvalu');
INSERT INTO `pais` VALUES ('100', 'Ukraine');
INSERT INTO `pais` VALUES ('101', 'United Arab Emirates');
INSERT INTO `pais` VALUES ('102', 'United Kingdom');
INSERT INTO `pais` VALUES ('103', 'United States');
INSERT INTO `pais` VALUES ('104', 'Venezuela');
INSERT INTO `pais` VALUES ('105', 'Vietnam');
INSERT INTO `pais` VALUES ('106', 'Virgin Islands, U.S.');
INSERT INTO `pais` VALUES ('107', 'Yemen');
INSERT INTO `pais` VALUES ('108', 'Yugoslavia');
INSERT INTO `pais` VALUES ('109', 'Zambia');